# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# TODO: Heroku needs a config/secrets.yml file on github, but I am having difficulty not pushing up changes to this file even with config/secrets.yml in .gitignore file. Trying git rm --cached config/secrets.yml deletes the whole file, which lead me back to the original problem of not having a config/secrets on github
development:
  secret_key_base:    470dc5160b7de71361a7bf17d065c1c307804a8d48318939eae0c6ddd91e4f80eac4ba2392a38424cee3d88741353e8b7900dfd966ef86676c025bcb7772223a

  # Amazon credentials
  aws_access_key_id:        AKIAJIS77C7YFPN65Q4A
  aws_cloud_front:          dfg4bcc9lmlk6.cloudfront.net
  aws_region:               us-west-2
  aws_secret_access_key:    Z5tIMQelmZEVR48vxi50bEaiUnDfGljI2GqHn4bC
  s3_bucket_name:           downeyd27
  s3_host_alias:            http://s3-us-west-2.amazonaws.com

  # Twilio credentials
  twilio_number:            +15038500760
  twilio_sid:               AC38d51301a70e16e81a331eb76cc65316
  twilio_token:             b039909b532b8b7048b21750403c9520

test:
  secret_key_base:    f3b6685ad6c34e1f61e230d0f46a8644cc6dec684a1b85840ac73856416628fbf99690bf0777e39cb9f59b00dafe71900ed40bcf343d9f2a92dc63d0a0625cb4

  # Amazon credentials
  aws_access_key_id:        AKIAJIS77C7YFPN65Q4A
  aws_cloud_front:          dfg4bcc9lmlk6.cloudfront.net
  aws_region:               us-west-2
  aws_secret_access_key:    Z5tIMQelmZEVR48vxi50bEaiUnDfGljI2GqHn4bC
  s3_bucket_name:           downeyd27
  s3_host_alias:            http://s3-us-west-2.amazonaws.com

  # Twilio credentials
  twilio_number:            +15038500760
  twilio_sid:               AC38d51301a70e16e81a331eb76cc65316
  twilio_token:             b039909b532b8b7048b21750403c9520


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:           <%= ENV["SECRET_KEY_BASE"] %>
  # Amazon credentials
  s3_bucket_name:            <%= ENV["S3_BUCKET_NAME"] %>
  aws_secret_access_key:     <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_access_key_id:         <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_region:                <%= ENV["AWS_REGION"] %>
  aws_cloud_front:           <%= ENV["AWS_CLOUD_FRONT"] %>

  # Twilio credentials
  twilio_token:  <%= ENV["TWILIO_TOKEN"] %>
  twilio_sid:    <%= ENV["TWILIO_SID"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
